Repository Vizzuality/devismos, pull requests merged in 2021-06, with the labels that each got.

#19 Add Sci team docs
  _docs/frontismos/strategy-2021/funtional-areas/science.md
  _docs/sciteam/index.md
  _docs/sciteam/recurrent-activities/capacity-meetings.md
  _docs/sciteam/recurrent-activities/index.md
  _docs/sciteam/recurrent-activities/pairing.md
  _docs/sciteam/resources/create-role.md
  _docs/sciteam/resources/index.md
  _docs/sciteam/roles/bd-rep.md
  _docs/sciteam/roles/capacity.md
  _docs/sciteam/roles/index.md
  _docs/sciteam/roles/standardisation-quality.md
  _docs/sciteam/roles/strategy.md
  _docs/sciteam/roles/support.md
  _docs/sciteam/strategy-2021/funtional-areas/backend.md
  _docs/sciteam/strategy-2021/funtional-areas/business-development.md
  _docs/sciteam/strategy-2021/funtional-areas/communications.md
  _docs/sciteam/strategy-2021/funtional-areas/design-research.md
  _docs/sciteam/strategy-2021/funtional-areas/executive.md
  _docs/sciteam/strategy-2021/funtional-areas/index.md
  _docs/sciteam/strategy-2021/funtional-areas/operations.md
  _docs/sciteam/strategy-2021/funtional-areas/people-and-culture.md
  _docs/sciteam/strategy-2021/funtional-areas/project-management.md
  _docs/sciteam/strategy-2021/index.md
  _docs/sciteam/strategy-2021/initiatives-directory/index.md
Labels: ready to review

#20 Update readme content
  README.md
Labels: BE(FA), FE(FA), SCI(FA), ready to review

#22 Chore/sci support definition
  _docs/sciteam/index.md
  _docs/sciteam/roles/index.md
  _docs/sciteam/roles/support.md
Labels: SCI(FA), ready to review

#16 [BE] Strategy role definition
  _docs/backenders/strategy-2021/roles/index.md
  _docs/backenders/strategy-2021/roles/strategy.md
Labels: BE(FA), ready to review

#17 Add Hiring role definition
  _docs/backenders/strategy-2021/roles/hiring.md
  _docs/backenders/strategy-2021/roles/index.md
Labels: BE(FA), ready to review

#23 [BE] Quality role definition
  _docs/backenders/strategy-2021/roles/index.md
  _docs/backenders/strategy-2021/roles/quality.md
Labels: BE(FA), ready to review

#15 Adds description for capacity
  _docs/backenders/strategy-2021/roles/capacity.md
  _docs/backenders/strategy-2021/roles/index.md
Labels: BE(FA), ready to review
